name: CI - Test Automation

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # 1. リポジトリをチェックアウト
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Node.jsをセットアップ
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. 依存関係をインストール
      - name: Install dependencies
        run: npm install

      # 4. テストを実行
      - name: Run tests
        run: npm test

      # 5. テストカバレッジを生成（オプション）
      - name: Run tests with coverage
        run: npx jest --coverage

      # 6. カバレッジ結果を保存（オプション）
      - name: Upload coverage to GitHub
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: coverage/
